os:
  - linux
  - windows

language: node_js

cache:
  npm: true

node_js:
  - "10"
  - "12"
  - "14"

script:
  - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
      npm run eslint;
    fi
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
