language: node_js

sudo: false

cache: npm

node_js:
  - "10"
  - "12"
  - "node"

script:
  - npm run eslint
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls

dist: bionic
