language: node_js

sudo: false

cache:
  npm: true

node_js:
  - "8"
  - "10"
  - "12"
  - "13"

script:
  - npm run eslint
  - npm run test-cov

after_script:
  - npm install coveralls
  - nyc report --reporter=text-lcov | coveralls
